[package]
name = "grep"
version = "0.0.0"
authors = ["patatahooligan <filwn.oikonomou@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
